repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.59.0"
    hooks:
      - id: terraform_fmt
        always_run: true
      - id: terraform_tflint
        always_run: true
        args:
          - args=--enable-rule=terraform_comment_syntax
          - args=--enable-rule=terraform_typed_variables
      # - id: checkov
      #   files: '.*/modules/($|/.*)'
      #   always_run: true