trigger: none
pr:
  - main
pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:latest run -a
      git add --all
      git commit -m "Updating FMT and Docs"
      git push
    displayName: Perform Pre-Commit Checks
