trigger: none
pool:
  vmImage: ubuntu-latest


steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:latest run -a
    displayName: Perform Pre-Commit Checks