location               = "South Central US"
resource_group_name    = "controller-deploy-rg"
vnet_name              = "controller-vnet"
controller_customer_id = ""
admin_email            = ""
ssh_public_key         = ""
