variable "s3_bucket_name" {
  description = "The name of the S3 Bucket to store Firewall Bootstrap."
  type        = string
  default     = ""
}

variable "s3_iam_role_name" {
  description = "The name of the iam role used to access S3 Bucket."
  type        = string
  default     = "aviatrix-s3-bootstrap-role"
}

variable "aws_key_pair_public_key" {
  description = "The key pair public ssh key to be used for EC2 Instance Deployments."
  type        = string
}

variable "aws_firewall_key_pair_name" {
  description = "The key pair name to be used for Firewall EC2 Instance Deployments."
  type        = string
  default     = "aviatrix-firenet-key"
}

variable "firewall_private_key_location" {
  description = "The location of the private key on the local machine to authenticate to palo firewall to change admin credentials."
  type        = string
  default     = ""
}

variable "firewall_password" {
  description = "Password used for the admin user of the firewall. If not provided then password will be autogenerated and stored in AWS Systems Manager Parameter Store."
  type        = string
  default     = ""
}

variable "store_firewall_password_in_ssm" {
  description = "Gives the option to store the firewall password in AWS Systems Manager Parameter Store to access."
  type        = bool
  default     = true
}

variable "aws_vpc_id" {
  description = "The VPC ID used for firewall instance."
  type        = string
}

variable "aviatrix_transit_primary_gateway_name" {
  description = "The name of the primary transit gateway."
  type        = string
}

variable "aviatrix_transit_ha_gateway_name" {
  description = "The name of the primary transit gateway."
  type        = string
}

variable "firewall_mgmt_primary_subnet" {
  description = "The primary subnet for firewall management."
  type        = string
}

variable "firewall_mgmt_ha_subnet" {
  description = "The ha subnet for firewall management."
  type        = string
}

variable "firewall_egress_primary_subnet" {
  description = "The primary subnet for firewall egress."
  type        = string
}

variable "firewall_egress_ha_subnet" {
  description = "The ha subnet for firewall egress."
  type        = string
}

variable "firewalls" {
  description = "The firewall instance information required for creating firewalls"
  type = list(object({
    name = string
  }))
  default = []
}

variable "firewall_image" {
  type        = string
  description = "The firewall image to be used to deploy the NGFW's"
  default     = "Palo Alto Networks VM-Series Next-Generation Firewall Bundle 1"
  validation {
    condition = contains(
      [
        "Palo Alto Networks VM-Series Next-Generation Firewall Bundle 1",
        "Palo Alto Networks VM-Series Next-Generation Firewall Bundle 1 [VM-300]",
        "Palo Alto Networks VM-Series Next-Generation Firewall Bundle 2",
        "Palo Alto Networks VM-Series Next-Generation Firewall Bundle 2 [VM-300]",
        "Palo Alto Networks VM-Series Next-Generation Firewall (BYOL)"
      ],
    var.firewall_image)
    error_message = "The firewall_image must be one of values in the condition statement."
  }
}

variable "firewall_image_version" {
  description = "The firewall image version specific to the NGFW vendor image"
  type        = string
  default     = "10.1.4"
}

variable "firewall_size" {
  description = "The firewall ec2 instance size."
  type        = string
  default     = "m5.xlarge"
}

locals {
  s3_bucket_name = length(var.s3_bucket_name) > 0 ? var.s3_bucket_name : "aviatrix-s3-bucket-${random_id.s3_bucket_random_id[0].hex}"
}
