name: Generate infracost estimates
on:
  pull_request:
    paths:
    - '**.tf'
    - '**.tfvars'
    - '**.tfvars.json'
jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    # - name: Terraform init
    #   run: terraform init

    # - name: Terraform plan
    #   run: terraform plan -out tfplan.binary -var-file="default.tfvars" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="avx_aviatrix_customer_id=${{ secrets.AVX_CUSTOMER_ID }}" -var="avx_account_email=${{ secrets.ADMIN_EMAIL }}" -var="avx_controller_admin_email=${{ secrets.ADMIN_EMAIL }}"


    # - name: Terraform show
    #   run: terraform show -json tfplan.binary > plan.json

    - name: Setup Infracost
      uses: infracost/actions/setup@v1
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    - name: Run Infracost
      run: infracost breakdown --format json --out-file=/tmp/infracost.json --config-file infracost.yml

    - name: Post the comment
      uses: infracost/actions/comment@v1
      with:
        path: /tmp/infracost.json
        behavior: update