name: Run Pre-Commit Checks
on:
  - pull_request

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    name: Pre-Commit Checks
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Pre-Commit
        run: |
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:v1.64.0 run -a
